### ISSUE TITLE
Reproducing Issue

### ISSUE THREAD

**Issue by Heisenberg1159** [xu737/PeFAD#1]
When I am reproducing your paper, the parameters in the SMD dataset's metrics usage script are much different from the metrics in the paper, and I would like to get the best parameters from your paper.
![image](https://github.com/user-attachments/assets/eda0e632-a826-421c-8929-18b4dd555983)

**Comment by xu737** [comment]
I would like to know if you are using GPT2 in 768 dimensions.  We are using a 1280-dimensional GPT-2 model. You can download the pytorch_model.bin file from https://huggingface.co/openai-community/gpt2-large and place it in the _gpt2-l_ folder, 
(Corresponds to the following code in the GPT4TS file: `self.gpt2 = GPT2Model.from_pretrained('gpt2-l', output_attentions=True, output_hidden_states=True)`), and then run the script file.
